#!/bin/bash

set -e

SOURCES_DIR=/tmp/artifacts

cp -rf ${SOURCES_DIR}/${OPTAWEB_DISTRIBUTION_WAR} ${JBOSS_HOME}/standalone/deployments/ROOT.war
touch ${JBOSS_HOME}/standalone/deployments/ROOT.war.dodeploy


chown -R jboss:root ${JBOSS_HOME}
chmod 0755 ${JBOSS_HOME}
chmod -R g+rwX ${JBOSS_HOME}
